site_name: Elyrii
site_description: Project overview, technical choices, and links to Mobile, Server, and AI documentation.
site_url: https://elyrii-epitech.github.io/Elyrii
repo_url: https://github.com/elyrii-epitech/Elyrii
theme:
  name: material
  features:
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
nav:
  - Home: index.md
  - Mobile:
      - Overview: mobile/index.md
      - Generated Docs: mobile/
  - Server:
      - Overview: server/index.md
      - Generated Docs: server/
  - AI:
      - Overview: ai/index.md
      - Generated Docs: ai/
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - def_list
  - attr_list
  - footnotes
extra:
  social:
    - icon: material/github
      link: https://github.com/elyrii-epitech/Elyrii
