"""Candidate-only context extraction. No persistence or response-prompt side effects."""

import asyncio
import json
import math
import re
from datetime import datetime
from pathlib import Path
from typing import Annotated, Literal, Union
from uuid import UUID
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import httpx
from pydantic import (
    BaseModel, ConfigDict, Field, JsonValue,
    field_validator, model_validator,
)


MAX_OUTPUT_BYTES = 32768
MAX_RESPONSE_BYTES = 65536
MAX_INPUT_BYTES = 24000
MAX_TOKENS = 2048
PROMPT_VERSION = "v1"


class ExtractionError(ValueError):
    """Extraction failed closed; callers must not treat this as an empty result."""


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)


Text = Annotated[str, Field(min_length=1, max_length=4000, pattern=r"\S")]
Identifier = Annotated[str, Field(pattern=r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")]


def instant(value: str) -> str:
    # Offset is mandatory; never interpret a date using the worker's local zone.
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)", value):
        raise ValueError("Expected an ISO timestamp with an explicit offset")
    datetime.fromisoformat(value.replace("Z", "+00:00"))
    return value


class Message(StrictModel):
    id: Identifier
    role: Literal["user", "assistant", "system"]
    content: Text
    messageAt: str
    # Optional trusted event instant supplied by the caller, not generated by AI.
    eventAt: str | None = None

    @field_validator("messageAt", "eventAt")
    @classmethod
    def timestamps(cls, value):
        return instant(value) if value is not None else value


class ExtractionRequest(StrictModel):
    source: Message
    context: Annotated[list[Message], Field(max_length=12)] = Field(default_factory=list)
    timezone: str

    @field_validator("timezone")
    @classmethod
    def known_timezone(cls, value):
        try:
            ZoneInfo(value)
        except (ZoneInfoNotFoundError, ValueError) as exc:
            raise ValueError("Expected an IANA timezone") from exc
        return value

    @model_validator(mode="after")
    def bounded_source(self):
        if self.source.role != "user":
            raise ValueError("Source must be a persisted user message")
        ids = [UUID(message.id) for message in [self.source, *self.context]]
        if len(ids) != len(set(ids)):
            raise ValueError("Duplicate message IDs")
        if len(self.model_dump_json().encode("utf-8")) > MAX_INPUT_BYTES:
            raise ValueError("Conversation exceeds the input byte limit")
        return self


class Provenance(StrictModel):
    origin: Literal["explicit", "inferred"]
    sourceMessageId: Identifier


class FactCandidate(Provenance):
    kind: Literal["fact", "preference"]
    key: Annotated[str, Field(min_length=1, max_length=200, pattern=r"\S")]
    value: JsonValue

    @field_validator("value")
    @classmethod
    def non_null_value(cls, value):
        if value is None:
            raise ValueError("Fact values cannot be null")
        return value


class MemoryCandidate(Provenance):
    kind: Literal["memory"]
    content: Annotated[str, Field(min_length=1, max_length=10000, pattern=r"\S")]
    retention: Literal["short_term", "long_term"]
    eventAt: str | None

    @field_validator("eventAt")
    @classmethod
    def event_timestamp(cls, value):
        return instant(value) if value is not None else value


Candidate = Annotated[Union[FactCandidate, MemoryCandidate], Field(discriminator="kind")]


class Proposal(StrictModel):
    candidate: Candidate
    evidence: Text
    certainty: Literal["certain", "uncertain"]
    category: Literal["stable_fact", "stable_preference", "temporary_emotion", "minor_event", "durable_life_event"]
    temporalExpression: Text | None

    @model_validator(mode="after")
    def classification(self):
        if self.candidate.origin == "inferred" and self.certainty != "uncertain":
            raise ValueError("Inferred candidates must preserve uncertainty")
        expected = {
            "stable_fact": "fact", "stable_preference": "preference",
            "temporary_emotion": "memory", "minor_event": "memory",
            "durable_life_event": "memory",
        }[self.category]
        if self.candidate.kind != expected:
            raise ValueError("Candidate kind does not match classification")
        if isinstance(self.candidate, MemoryCandidate):
            retention = "long_term" if self.category == "durable_life_event" else "short_term"
            if self.candidate.retention != retention:
                raise ValueError("Retention does not match classification")
        return self


class ExtractionResult(StrictModel):
    promptVersion: Literal["v1"]
    candidates: Annotated[list[Proposal], Field(max_length=8)]


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("Duplicate JSON key")
        result[key] = value
    return result


def _invalid_constant(value):
    raise ValueError("Non-finite JSON number")


def _finite_float(value):
    number = float(value)
    if not math.isfinite(number):
        raise ValueError("Non-finite JSON number")
    return number


def strict_json(raw):
    return json.loads(raw, object_pairs_hook=_unique_object,
                      parse_constant=_invalid_constant, parse_float=_finite_float)


def validate_output(raw: str, request: ExtractionRequest) -> ExtractionResult:
    """Reject the entire response on any invalid candidate; never salvage fragments."""
    try:
        if not isinstance(raw, str) or len(raw.encode("utf-8")) > MAX_OUTPUT_BYTES:
            raise ValueError("Output exceeds limit or is not text")
        result = ExtractionResult.model_validate(strict_json(raw))
        for proposal in result.candidates:
            candidate = proposal.candidate
            if candidate.sourceMessageId != request.source.id:
                raise ValueError("Candidate must cite the current source message")
            if proposal.evidence not in request.source.content:
                raise ValueError("Evidence must be an exact source quote")
            if proposal.temporalExpression is not None and proposal.temporalExpression not in request.source.content:
                raise ValueError("Temporal expression must be an exact source quote")
            if isinstance(candidate, MemoryCandidate) and candidate.eventAt is not None:
                # Relative/day-only dates have no exact instant: retain the words,
                # not a fabricated midnight. Explicit instants must be in evidence.
                if candidate.eventAt != request.source.eventAt and candidate.eventAt not in proposal.evidence:
                    raise ValueError("Event instant lacks exact supporting evidence")
        return result
    except (ValueError, TypeError, RecursionError) as exc:
        raise ExtractionError("Invalid extraction output") from exc


class ContextExtractor:
    """One bounded Ollama request, with an injected client for deterministic tests.

    The caller owns the HTTP client's lifetime and supplies persisted source data.
    No retries, JSON repair, logging of private messages, or database writes.
    """

    def __init__(self, client: httpx.AsyncClient, model: str, timeout: float = 20.0):
        if not model.strip() or not math.isfinite(timeout) or not 0 < timeout <= 60:
            raise ValueError("A model and timeout in (0, 60] seconds are required")
        self.client = client
        self.model = model
        self.timeout = timeout

    async def extract(self, request: ExtractionRequest) -> ExtractionResult:
        # Revalidate even constructed or mutated models at the trust boundary.
        request = ExtractionRequest.model_validate(request.model_dump())
        prompt = (Path(__file__).parent / "prompt" / "extraction" / "v1.txt").read_text(encoding="utf-8")
        payload = request.model_dump()
        # Assistant/system claims cannot supply evidence, including via context.
        payload["context"] = [m.model_dump() for m in request.context if m.role == "user"]
        body = {
            "model": self.model,
            "messages": [{"role": "system", "content": prompt},
                         {"role": "user", "content": json.dumps(payload, ensure_ascii=False)}],
            "stream": False,
            "format": ExtractionResult.model_json_schema(),
            "options": {"temperature": 0, "num_predict": MAX_TOKENS},
        }
        try:
            raw = await asyncio.wait_for(self._infer(body), timeout=self.timeout)
            return validate_output(raw, request)
        except (httpx.HTTPError, asyncio.TimeoutError, ValueError, KeyError, TypeError, RecursionError) as exc:
            raise ExtractionError("Context extraction failed") from exc

    async def _infer(self, body):
        async with self.client.stream("POST", "/api/chat", json=body, timeout=self.timeout) as response:
            response.raise_for_status()
            data = bytearray()
            async for chunk in response.aiter_bytes():
                if len(data) + len(chunk) > MAX_RESPONSE_BYTES:
                    raise ExtractionError("Inference response exceeds limit")
                data.extend(chunk)
            envelope = strict_json(data)
            if not isinstance(envelope, dict):
                raise ExtractionError("Invalid inference envelope")
            if envelope.get("done") is not True or envelope.get("done_reason") == "length":
                raise ExtractionError("Incomplete inference response")
            return envelope["message"]["content"]
