"""
Elyrii Evaluation Script
========================

This script evaluates the fine-tuned Elyrii model by:
1. Generating responses to a curated set of "emotional test prompts".
2. Calculating an 'Empathy Score' using a pre-trained sentiment analysis model.
3. Saving the results to a CSV file for review.

It loads the base Mistral model and applies your trained LoRA adapter.

Usage:
    python evaluate.py --adapter_path ./output/final_lora
"""

import os
import argparse
import logging
from typing import Tuple, List, Dict, Any

import torch
import pandas as pd
from tqdm import tqdm
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    PreTrainedModel,
    PreTrainedTokenizer,
    pipeline,
    Pipeline,
)
from peft import PeftModel
from elyrii_ai.prompt.system_prompt import get_system_prompt

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# --- Constants ---
BASE_MODEL_ID = os.getenv("AI_MODEL")
HF_TOKEN = os.getenv("HF_TOKEN")

# Test prompts designed to trigger emotional support responses
TEST_PROMPTS = [
    "I feel really lonely lately and I don't know how to make friends.",
    "My boss yelled at me today for a mistake I didn't make. I'm so angry.",
    "I'm anxious about my upcoming presentation. I feel like I'm going to fail.",
    "I just went through a breakup and everything hurts.",
    "I feel like I'm not good enough for anyone.",
]

SYSTEM_PROMPT = get_system_prompt()


def load_model_and_tokenizer(
    adapter_path: str,
) -> Tuple[PreTrainedModel, PreTrainedTokenizer]:
    """
    Loads the base Mistral model and merges the provided LoRA adapter.

    Args:
        adapter_path: The directory path containing the saved LoRA adapter.

    Returns:
        A tuple containing:
            - model: The loaded PeftModel (Base + Adapter).
            - tokenizer: The associated tokenizer.
    """
    logger.info(f"🏗️  Loading base model: {BASE_MODEL_ID}")

    # Load Base Model
    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        device_map="auto",
        torch_dtype=torch.float16,
        token=HF_TOKEN,
        load_in_8bit=True,  # Keep 8-bit for inference on consumer GPUs
    )

    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, token=HF_TOKEN)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Load Adapter
    logger.info(f"🔗 Loading LoRA adapter from: {adapter_path}")
    model = PeftModel.from_pretrained(model, adapter_path)

    return model, tokenizer


def generate_response(
    model: PreTrainedModel, tokenizer: PreTrainedTokenizer, prompt: str
) -> str:
    """
    Generates a response to a user prompt using the Elyrii persona.

    Args:
        model: The loaded language model.
        tokenizer: The loaded tokenizer.
        prompt: The user's input message.

    Returns:
        The string response generated by the model (stripped of special tokens).
    """

    # Format with the Chat Template
    messages = [{"role": "user", "content": f"{SYSTEM_PROMPT}\n\n{prompt}"}]

    inputs = tokenizer.apply_chat_template(
        messages, return_tensors="pt", add_generation_prompt=True
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            inputs,
            max_new_tokens=256,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.pad_token_id,
        )

    # Decode and strip the prompt
    full_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract just the assistant's response (naive split by [/INST])
    # Mistral template usually looks like: [INST] ... [/INST] Response
    if "[/INST]" in full_text:
        return full_text.split("[/INST]")[-1].strip()

    # Fallback if template stripping fails (unlikely with correct decoding)
    # Remove the system prompt and user prompt roughly
    response = full_text.replace(SYSTEM_PROMPT, "").replace(prompt, "").strip()
    return response


def score_empathy(text: str, analyzer: Pipeline) -> int:
    """
    Scores the empathy/positivity of a text using a sentiment analysis pipeline.

    Args:
        text: The response text to evaluate.
        analyzer: A HuggingFace sentiment-analysis pipeline.

    Returns:
        An integer score from 1 to 5 (1 = Negative/Hostile, 5 = Empathetic/Positive).
    """
    # We use a multilingual sentiment model (1-5 stars)
    # 'nlptown/bert-base-multilingual-uncased-sentiment' is a good proxy for tone
    result = analyzer(text[:512])[0]  # Truncate to 512 for BERT

    # Map label '1 star' -> 1, '5 stars' -> 5
    stars = int(result["label"].split()[0])
    return stars


def main():
    """Main execution flow for evaluation."""
    parser = argparse.ArgumentParser(description="Evaluate Elyrii Model")
    parser.add_argument(
        "--adapter_path",
        type=str,
        required=True,
        help="Path to the LoRA adapter folder",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        default="evaluation_results.csv",
        help="Output CSV file",
    )
    args = parser.parse_args()

    # 1. Load Generation Model
    model, tokenizer = load_model_and_tokenizer(args.adapter_path)

    # 2. Load Judge Model (Sentiment/Empathy)
    logger.info("⚖️  Loading sentiment analyzer (The Judge)...")
    judge = pipeline(
        "sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment"
    )

    results = []

    logger.info("🧪 Starting evaluation loop...")
    for prompt in tqdm(TEST_PROMPTS, desc="Generating"):
        # Generate
        response = generate_response(model, tokenizer, prompt)

        # Score
        score = score_empathy(response, judge)

        results.append(
            {
                "User Prompt": prompt,
                "Elyrii Response": response,
                "Empathy Score (1-5)": score,
            }
        )

    # 3. Save Results
    df = pd.DataFrame(results)
    avg_score = df["Empathy Score (1-5)"].mean()

    logger.info(f"📊 Average Empathy Score: {avg_score:.2f}/5.0")

    df.to_csv(args.output_file, index=False)
    logger.info(f"💾 Results saved to {args.output_file}")

    # Print preview
    print("\n--- Preview ---")
    print(df[["User Prompt", "Elyrii Response"]].head(2).to_markdown(index=False))


if __name__ == "__main__":
    main()
