services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
        - PORT=${PORT:-3000}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=${DB_NAME}
        - REDPANDA_HOST=${REDPANDA_HOST}
        - REDPANDA_PORT=${REDPANDA_PORT}
        - SECRET_KEY=${SECRET_KEY:-super-secret-key}
        - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY:-super-refresh-secret-key}
        - NODE_ENV=production
    networks:
      - elyrii_net
    depends_on:
        redpanda:
            condition: service_healthy
        postgres:
            condition: service_healthy
    command: sh -c "sleep 5 && bun run db:push && bun run start"


  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "9644:9644"
    command: >
      redpanda start
        --overprovisioned
        --smp 1
        --memory 1G
        --reserve-memory 0M
        --check=false
        --node-id=1
        --kafka-addr PLAINTEXT://0.0.0.0:9092
        --advertise-kafka-addr PLAINTEXT://redpanda:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - elyrii_net

  redpanda_console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda_console
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKERS: redpanda:9092
      REDPANDA_ADMIN_URL: http://redpanda:9644
    networks:
      - elyrii_net

  postgres:
    image: postgres:16-alpine
    container_name: postgres_elyrii
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh
    networks:
      - elyrii_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  redpanda_data:
  pg_data:

networks:
  elyrii_net:
    driver: bridge
