import { createFactory } from "hono/factory";
import QuestRepository from "../../repository/quest.repository";
import type { HonoEnv } from "../../utils/hono.types";
import { z } from "zod";
import { sValidator } from "@hono/standard-validator";
import { describeRoute } from "hono-openapi";
import QuestLogic from "./quest.logic";

/**
 * Controller that defines HTTP handlers for gamified challenges (quests).
 * 
 * @remarks
 * This controller handles:
 * - Retrieving active, completed, and pending challenges
 * - Accepting or rejecting AI-proposed challenges
 * - Creating new challenge proposals (internal use, typically by AI)
 */
class QuestController {
    private readonly factory = createFactory<HonoEnv>();
    private readonly questRepository: QuestRepository = new QuestRepository();
    private readonly questLogic: QuestLogic = new QuestLogic();

    /**
     * Handler for retrieving active challenges for the user.
     * 
     * @param ctx - Hono Context
     * @returns JSON array of active challenges
     */
    public readonly getActiveChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Active Challenges",
            description: "Retrieve all active challenges for the authenticated user.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of active challenges" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challenges = await this.questRepository.getUserChallenges(userId, 'ACTIVE');
            return ctx.json(challenges);
        }
    );

    /**
     * Handler for retrieving completed challenges for the user.
     * 
     * @param ctx - Hono Context
     * @returns JSON array of completed challenges
     */
    public readonly getCompletedChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Completed Challenges",
            description: "Retrieve all completed challenges for the authenticated user.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of completed challenges" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challenges = await this.questRepository.getUserChallenges(userId, 'COMPLETED');
            return ctx.json(challenges);
        }
    );

    /**
     * Handler for retrieving pending challenge proposals for the user.
     * 
     * @remarks
     * Pending challenges are usually proposals generated by the AI that the user hasn't accepted yet.
     * 
     * @param ctx - Hono Context
     * @returns JSON array of pending challenges
     */
    public readonly getPendingChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Pending Proposals",
            description: "Retrieve all pending challenge proposals for the authenticated user.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of pending challenge proposals" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challenges = await this.questRepository.getUserChallenges(userId, 'PENDING');
            return ctx.json(challenges);
        }
    );

    /**
     * Handler for accepting a challenge proposal.
     * 
     * @remarks
     * Transitions a challenge from 'PENDING' to 'ACTIVE'.
     * 
     * @param ctx - Hono Context
     * @param ctx.req.param.challengeId - ID of the challenge to accept
     * @returns JSON object of the updated challenge
     */
    public readonly acceptChallenge = this.factory.createHandlers(
        describeRoute({
            summary: "Accept Challenge",
            description: "Accept a pending challenge proposal, making it active.",
            tags: ["Quest"],
            responses: {
                200: { description: "Challenge accepted successfully" },
                400: { description: "Challenge ID is required" },
                500: { description: "Failed to accept challenge" }
            }
        }),
        async (ctx) => {
            const challengeId = ctx.req.param("challengeId");
            if (!challengeId) {
                return ctx.json({ error: "Challenge ID is required" }, 400);
            }
            try {
                const updated = await this.questRepository.updateUserChallengeStatus(challengeId, 'ACTIVE');
                return ctx.json(updated);
            } catch (e) {
                return ctx.json({ error: "Failed to accept challenge" }, 500);
            }
        }
    );

    /**
     * Handler for rejecting a challenge proposal.
     * 
     * @remarks
     * Transitions a challenge from 'PENDING' to 'REJECTED'.
     * 
     * @param ctx - Hono Context
     * @param ctx.req.param.challengeId - ID of the challenge to reject
     * @returns JSON object of the updated challenge
     */
    public readonly rejectChallenge = this.factory.createHandlers(
        describeRoute({
            summary: "Reject Challenge",
            description: "Reject a pending challenge proposal.",
            tags: ["Quest"],
            responses: {
                200: { description: "Challenge rejected successfully" },
                400: { description: "Challenge ID is required" },
                500: { description: "Failed to reject challenge" }
            }
        }),
        async (ctx) => {
            const challengeId = ctx.req.param("challengeId");
            if (!challengeId) {
                return ctx.json({ error: "Challenge ID is required" }, 400);
            }
            try {
                const updated = await this.questRepository.updateUserChallengeStatus(challengeId, 'REJECTED');
                return ctx.json(updated);
            } catch (e) {
                return ctx.json({ error: "Failed to reject challenge" }, 500);
            }
        }
    );

    /**
     * Handler for retrieving SYSTEM challenges not yet started by the user.
     */
    public readonly getAvailableChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Available Challenges",
            description: "Retrieve SYSTEM challenges the user hasn't started or completed yet.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of available challenges" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challenges = await this.questRepository.getAvailableChallenges(userId);
            return ctx.json(challenges);
        }
    );

    /**
     * Handler for starting a SYSTEM challenge.
     * Assigns the challenge to the user with status ACTIVE.
     */
    public readonly startChallenge = this.factory.createHandlers(
        describeRoute({
            summary: "Start Challenge",
            description: "Start a SYSTEM challenge by assigning it to the user with ACTIVE status.",
            tags: ["Quest"],
            responses: {
                201: { description: "Challenge started successfully" },
                400: { description: "Challenge ID is required" },
                404: { description: "Challenge not found" },
                409: { description: "Challenge already active or completed" },
                500: { description: "Failed to start challenge" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challengeId = ctx.req.param("challengeId");
            if (!challengeId) {
                return ctx.json({ error: "Challenge ID is required" }, 400);
            }

            // Vérifier que le défi existe
            const template = await this.questRepository.getChallengeTemplateById(challengeId);
            if (!template) {
                return ctx.json({ error: "Challenge not found" }, 404);
            }

            try {
                // Initialiser la progression à zéro pour chaque condition
                const conditions = template.conditions as { target: number }[];
                const initialProgress: Record<string, { current: number; target: number; completed: boolean; updatedAt: string }> = {};
                conditions.forEach((cond, i) => {
                    initialProgress[`condition_${i}`] = {
                        current: 0,
                        target: cond.target,
                        completed: false,
                        updatedAt: new Date().toISOString(),
                    };
                });

                const userChallenge = await this.questRepository.assignChallengeToUser({
                    userId,
                    challengeId,
                    status: 'ACTIVE',
                    progress: initialProgress,
                });

                return ctx.json({ challenge: template, userChallenge }, 201);
            } catch (e) {
                return ctx.json({ error: "Failed to start challenge" }, 500);
            }
        }
    );

    /**
     * Handler for creating a new challenge proposal.
     * 
     * @remarks
     * This endpoint is typically called by internal systems or AI agents to propose a new challenge to a user.
     * It creates a challenge template and assigns it to the user with 'PENDING' status.
     * 
     * @param ctx - Hono Context containing the JSON body
     * @param ctx.req.valid.json - Validated body: { title, description?, conditions, aggregator, constraints, userId }
     * @returns JSON object containing the created template and user challenge assignment
     */
    public readonly createProposal = this.factory.createHandlers(
        describeRoute({
            summary: "Create Challenge Proposal",
            description: "Create a new challenge proposal for a user (Internal/AI).",
            tags: ["Quest"],
            responses: {
                201: { description: "Proposal created successfully" },
                400: { description: "Invalid request body" }
            }
        }),
        sValidator("json", z.object({
            title: z.string(),
            description: z.string().optional(),
            conditions: z.any(),
            aggregator: z.enum(['ALL', 'ANY']).default('ALL'),
            constraints: z.any(),
            userId: z.string().uuid()
        })),
        async (ctx) => {
            const body = ctx.req.valid("json");
            
            const template = await this.questRepository.createChallengeTemplate({
                title: body.title,
                description: body.description,
                source: 'AI',
                conditions: body.conditions,
                aggregator: body.aggregator,
                constraints: body.constraints
            });

            const userChallenge = await this.questRepository.assignChallengeToUser({
                userId: body.userId,
                challengeId: template.id,
                status: 'PENDING',
                progress: {}
            });

            return ctx.json({ template, userChallenge }, 201);
        }
    );
}

export default QuestController;
