import { createFactory } from "hono/factory";
import QuestRepository from "../../repository/quest.repository";
import type { HonoEnv } from "../../utils/hono.types";
import { z } from "zod";
import { sValidator } from "@hono/standard-validator";
import { describeRoute } from "hono-openapi";
import QuestLogic from "./quest.logic";

/**
 * Controller that defines HTTP handlers for gamified challenges (quests).
 * 
 * @remarks
 * This controller handles:
 * - Retrieving active, completed, and pending challenges
 * - Accepting or rejecting AI-proposed challenges
 * - Creating new challenge proposals (internal use, typically by AI)
 */
class QuestController {
    private readonly factory = createFactory<HonoEnv>();
    private readonly questRepository: QuestRepository = new QuestRepository();
    private readonly questLogic: QuestLogic = new QuestLogic();

    private sortUserChallenges<T extends { createdAt: Date | null; completedAt: Date | null; challenge: { rewardPoints: number } }>(
        rows: T[],
        sort?: string,
    ): T[] {
        const normalized = (sort || "newest").toLowerCase();
        const sorted = [...rows];
        if (normalized === "oldest") {
            sorted.sort((a, b) => (a.createdAt?.getTime() ?? 0) - (b.createdAt?.getTime() ?? 0));
            return sorted;
        }
        if (normalized === "points_desc") {
            sorted.sort((a, b) => (b.challenge.rewardPoints ?? 0) - (a.challenge.rewardPoints ?? 0));
            return sorted;
        }
        if (normalized === "completed_desc") {
            sorted.sort((a, b) => (b.completedAt?.getTime() ?? 0) - (a.completedAt?.getTime() ?? 0));
            return sorted;
        }
        sorted.sort((a, b) => (b.createdAt?.getTime() ?? 0) - (a.createdAt?.getTime() ?? 0));
        return sorted;
    }

    /**
     * Handler for retrieving active challenges for the user.
     * 
     * @param ctx - Hono Context
     * @returns JSON array of active challenges
     */
    public readonly getActiveChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Active Challenges",
            description: "Retrieve all active challenges for the authenticated user.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of active challenges" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const sort = ctx.req.query("sort");
            const limit = Math.min(Math.max(Number(ctx.req.query("limit") || 100), 1), 200);
            const challenges = await this.questRepository.getUserChallenges(userId, 'ACTIVE');
            return ctx.json(this.sortUserChallenges(challenges, sort).slice(0, limit));
        }
    );

    /**
     * Handler for retrieving completed challenges for the user.
     * 
     * @param ctx - Hono Context
     * @returns JSON array of completed challenges
     */
    public readonly getCompletedChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Completed Challenges",
            description: "Retrieve all completed challenges for the authenticated user.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of completed challenges" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const sort = ctx.req.query("sort");
            const limit = Math.min(Math.max(Number(ctx.req.query("limit") || 100), 1), 200);
            const challenges = await this.questRepository.getUserChallenges(userId, 'COMPLETED');
            return ctx.json(this.sortUserChallenges(challenges, sort).slice(0, limit));
        }
    );

    /**
     * Handler for retrieving pending challenge proposals for the user.
     * 
     * @remarks
     * Pending challenges are usually proposals generated by the AI that the user hasn't accepted yet.
     * 
     * @param ctx - Hono Context
     * @returns JSON array of pending challenges
     */
    public readonly getPendingChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Pending Proposals",
            description: "Retrieve all pending challenge proposals for the authenticated user.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of pending challenge proposals" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const sort = ctx.req.query("sort");
            const limit = Math.min(Math.max(Number(ctx.req.query("limit") || 100), 1), 200);
            const challenges = await this.questRepository.getUserChallenges(userId, 'PENDING');
            return ctx.json(this.sortUserChallenges(challenges, sort).slice(0, limit));
        }
    );

    public readonly listChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "List Challenges",
            description: "List user challenges with optional status filter and sorting.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of challenges" },
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const status = ctx.req.query("status");
            const sort = ctx.req.query("sort");
            const limit = Math.min(Math.max(Number(ctx.req.query("limit") || 100), 1), 200);
            const allowedStatus = new Set(["PENDING", "ACTIVE", "COMPLETED", "REJECTED", "SKIPPED", "EXPIRED"]);
            const normalizedStatus = status?.toUpperCase();
            const finalStatus = normalizedStatus && allowedStatus.has(normalizedStatus) ? normalizedStatus : undefined;
            const challenges = await this.questRepository.getUserChallenges(userId, finalStatus);
            return ctx.json(this.sortUserChallenges(challenges, sort).slice(0, limit), 200);
        }
    );

    /**
     * Handler for accepting a challenge proposal.
     * 
     * @remarks
     * Transitions a challenge from 'PENDING' to 'ACTIVE'.
     * 
     * @param ctx - Hono Context
     * @param ctx.req.param.challengeId - ID of the challenge to accept
     * @returns JSON object of the updated challenge
     */
    public readonly acceptChallenge = this.factory.createHandlers(
        describeRoute({
            summary: "Accept Challenge",
            description: "Accept a pending challenge proposal, making it active.",
            tags: ["Quest"],
            responses: {
                200: { description: "Challenge accepted successfully" },
                400: { description: "Challenge ID is required" },
                500: { description: "Failed to accept challenge" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challengeId = ctx.req.param("challengeId");
            if (!challengeId) {
                return ctx.json({ error: "Challenge ID is required" }, 400);
            }

            const userChallenge = await this.questRepository.getUserChallengeByIdForUser(challengeId, userId);
            if (!userChallenge) {
                return ctx.json({ error: "Challenge not found" }, 404);
            }
            if (userChallenge.status !== 'PENDING') {
                return ctx.json({ error: "Challenge is not pending" }, 409);
            }
            try {
                const updated = await this.questRepository.updateUserChallengeStatusForUser(challengeId, userId, 'ACTIVE');
                return ctx.json(updated);
            } catch (e) {
                return ctx.json({ error: "Failed to accept challenge" }, 500);
            }
        }
    );

    /**
     * Handler for rejecting a challenge proposal.
     * 
     * @remarks
     * Transitions a challenge from 'PENDING' to 'REJECTED'.
     * 
     * @param ctx - Hono Context
     * @param ctx.req.param.challengeId - ID of the challenge to reject
     * @returns JSON object of the updated challenge
     */
    public readonly rejectChallenge = this.factory.createHandlers(
        describeRoute({
            summary: "Reject Challenge",
            description: "Reject a pending challenge proposal.",
            tags: ["Quest"],
            responses: {
                200: { description: "Challenge rejected successfully" },
                400: { description: "Challenge ID is required" },
                500: { description: "Failed to reject challenge" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challengeId = ctx.req.param("challengeId");
            if (!challengeId) {
                return ctx.json({ error: "Challenge ID is required" }, 400);
            }

            const userChallenge = await this.questRepository.getUserChallengeByIdForUser(challengeId, userId);
            if (!userChallenge) {
                return ctx.json({ error: "Challenge not found" }, 404);
            }
            if (userChallenge.status !== 'PENDING') {
                return ctx.json({ error: "Challenge is not pending" }, 409);
            }
            try {
                const updated = await this.questRepository.updateUserChallengeStatusForUser(challengeId, userId, 'REJECTED');
                return ctx.json(updated);
            } catch (e) {
                return ctx.json({ error: "Failed to reject challenge" }, 500);
            }
        }
    );

    /**
     * Handler for retrieving SYSTEM challenges not yet started by the user.
     */
    public readonly getAvailableChallenges = this.factory.createHandlers(
        describeRoute({
            summary: "Get Available Challenges",
            description: "Retrieve SYSTEM challenges the user hasn't started or completed yet.",
            tags: ["Quest"],
            responses: {
                200: { description: "List of available challenges" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const sort = (ctx.req.query("sort") || "newest").toLowerCase();
            const limit = Math.min(Math.max(Number(ctx.req.query("limit") || 100), 1), 200);
            const challenges = await this.questRepository.getAvailableChallenges(userId);
            const sorted = [...challenges];
            if (sort === "oldest") {
                sorted.sort((a, b) => (a.createdAt?.getTime() ?? 0) - (b.createdAt?.getTime() ?? 0));
            } else if (sort === "points_desc") {
                sorted.sort((a, b) => (b.rewardPoints ?? 0) - (a.rewardPoints ?? 0));
            } else {
                sorted.sort((a, b) => (b.createdAt?.getTime() ?? 0) - (a.createdAt?.getTime() ?? 0));
            }
            return ctx.json(sorted.slice(0, limit));
        }
    );

    /**
     * Handler for starting a SYSTEM challenge.
     * Assigns the challenge to the user with status ACTIVE.
     */
    public readonly startChallenge = this.factory.createHandlers(
        describeRoute({
            summary: "Start Challenge",
            description: "Start a SYSTEM challenge by assigning it to the user with ACTIVE status.",
            tags: ["Quest"],
            responses: {
                201: { description: "Challenge started successfully" },
                400: { description: "Challenge ID is required" },
                404: { description: "Challenge not found" },
                409: { description: "Challenge already active or completed" },
                500: { description: "Failed to start challenge" }
            }
        }),
        async (ctx) => {
            const userId = ctx.get("user").userId;
            const challengeId = ctx.req.param("challengeId");
            if (!challengeId) {
                return ctx.json({ error: "Challenge ID is required" }, 400);
            }

            // Vérifier que le défi existe
            const template = await this.questRepository.getChallengeTemplateById(challengeId);
            if (!template) {
                return ctx.json({ error: "Challenge not found" }, 404);
            }

            try {
                // Initialiser la progression à zéro pour chaque condition
                const conditions = template.conditions as { target: number }[];
                const initialProgress: Record<string, { current: number; target: number; completed: boolean; updatedAt: string }> = {};
                conditions.forEach((cond, i) => {
                    initialProgress[`condition_${i}`] = {
                        current: 0,
                        target: cond.target,
                        completed: false,
                        updatedAt: new Date().toISOString(),
                    };
                });

                const existingAssignment = await this.questRepository.getUserChallengeAssignment(userId, challengeId);
                if (existingAssignment && (existingAssignment.status === 'ACTIVE' || existingAssignment.status === 'COMPLETED')) {
                    return ctx.json({ error: "Challenge already active or completed" }, 409);
                }

                if (existingAssignment) {
                    const updated = await this.questRepository.updateUserChallengeStatusForUser(
                        existingAssignment.id,
                        userId,
                        'ACTIVE',
                        initialProgress,
                    );
                    return ctx.json({ challenge: template, userChallenge: updated }, 200);
                }

                const userChallenge = await this.questRepository.assignChallengeToUser({
                    userId,
                    challengeId,
                    status: 'ACTIVE',
                    progress: initialProgress,
                });

                return ctx.json({ challenge: template, userChallenge }, 201);
            } catch (e) {
                return ctx.json({ error: "Failed to start challenge" }, 500);
            }
        }
    );

    /**
     * Handler for creating a new challenge proposal.
     * 
     * @remarks
     * This endpoint is typically called by internal systems or AI agents to propose a new challenge to a user.
     * It creates a challenge template and assigns it to the user with 'PENDING' status.
     * 
     * @param ctx - Hono Context containing the JSON body
     * @param ctx.req.valid.json - Validated body: { title, description?, conditions, aggregator, constraints, userId }
     * @returns JSON object containing the created template and user challenge assignment
     */
    public readonly createProposal = this.factory.createHandlers(
        describeRoute({
            summary: "Create Challenge Proposal",
            description: "Create a new challenge proposal for a user (Internal/AI).",
            tags: ["Quest"],
            responses: {
                201: { description: "Proposal created successfully" },
                400: { description: "Invalid request body" }
            }
        }),
        sValidator("json", z.object({
            title: z.string(),
            description: z.string().optional(),
            conditions: z.any(),
            aggregator: z.enum(['ALL', 'ANY']).default('ALL'),
            constraints: z.any(),
            userId: z.string().uuid()
        })),
        async (ctx) => {
            const body = ctx.req.valid("json");
            
            const template = await this.questRepository.createChallengeTemplate({
                title: body.title,
                description: body.description,
                source: 'AI',
                conditions: body.conditions,
                aggregator: body.aggregator,
                constraints: body.constraints
            });

            const userChallenge = await this.questRepository.assignChallengeToUser({
                userId: body.userId,
                challengeId: template.id,
                status: 'PENDING',
                progress: {}
            });

            return ctx.json({ template, userChallenge }, 201);
        }
    );
}

export default QuestController;
