name: Backend Docker Build
permissions:
  contents: read

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: elyrii_server
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ACCESS_JWT_SIGN_KEY: ${{ secrets.ACCESS_JWT_SIGN_KEY }}
      REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker images
        run: |
          echo "Building monolithic backend image..."
          docker compose build