name: Flutter Style, Test & Docs

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: elyrii_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Static analysis
        run: flutter analyze

      - name: Run unit tests
        run: flutter test

      - name: Generate documentation
        run: flutter pub global activate dartdoc && flutter pub global run dartdoc

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: dartdoc-html
          path: elyrii_app/doc/api/