on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push mirror to target
        env:
          TARGET_REPO: EpitechPromo2027/G-EIP-600-PAR-6-1-eip-rafael.sapalo-esteves
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          # Add target remote using PAT
          git remote add target https://x-access-token:${TARGET_PAT}@github.com/${TARGET_REPO}.git

          git push --mirror target